# name: Deploy CI
# on:
#   push:
#     branches: [main]
#   pull_request:
#     types: [opened, synchronize, reopened]
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     if: "!contains(github.event.head_commit.message, '[skip ci]')"
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Deploy to Vercel Action
#         uses: BetaHuhn/deploy-to-vercel-action@latest
#         with:
#           GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
#           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#           VERCEL_ORG_ID: ${{ secrets.ORGID }}
#           VERCEL_PROJECT_ID: ${{ secrets.PROJECTID }}
name: deploy website
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #  your build commands
      - run: npm install
      - run: npm run test
      - run: npm run build
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.DEPLOY_TOKEN }} #Optional
          vercel-args: "--prod" #Optional
          vercel-org-id: ${{ secrets.ORGID}} #Required
          vercel-project-id: ${{ secrets.PROJECTID}} #Required
          working-directory: ./sub-directory
