name: "test-every-push"

on: push
jobs:
  test:
    name: test-every-push
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
