name: "test-every-push"

on: push
jobs:
  test:
    name: test-every-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - run: npm run lint
        if: ${{ always() }}
      - run: npm run test
        if: ${{ always() }}
